pub mod _01_generics;
pub mod _02_functions;
pub mod _03_implementation;
pub mod _04_traits;
// pub mod _05_bounds;
// pub mod _06_bounds_testcase;
// pub mod _07_multiple_bounds;
// pub mod _08_where_clauses;
// pub mod _09_new_type_idiom;
// pub mod _10_associated_items_the_problem;
// pub mod _11_associated_items_types;
// pub mod _12_phantom_type_parameters;
// pub mod _13_phantom_type_parameters_testcase;